/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package twitter.cc.nl;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;

import android.content.Intent;
import android.app.Activity;
import android.content.pm.PackageManager;
import android.content.pm.ResolveInfo;
import android.content.pm.ActivityInfo;
import android.content.ComponentName;
import android.content.pm.ActivityInfo;

import java.util.List;
import java.lang.Exception;

@Kroll.module(name="ShareToTwitter", id="twitter.cc.nl")
public class ShareToTwitterModule extends KrollModule
{

	// Standard Debugging variables
	private static final String LCAT = "ShareToTwitterModule";
	private static final boolean DBG = TiConfig.LOGD;
    
	public ShareToTwitterModule( ){
		super( );
	}

	@Kroll.onAppCreate
	public static void onAppCreate( TiApplication app ) { }

	// Methods
	@Kroll.method
	public boolean share( String text )
	{
        try {
            final String[ ] twitterApps = {
                "twitter",
                "twidroid",
                "handmark.tweetcaster",
                "thedeck.android"
            };
            
            TiApplication appContext = TiApplication.getInstance( );
            Activity activity = appContext.getCurrentActivity( );
            
            Intent tweetIntent = new Intent( Intent.ACTION_SEND );
            tweetIntent.putExtra( Intent.EXTRA_TEXT, text );
            tweetIntent.setType( "text/plain" );
            
            PackageManager pm = appContext.getPackageManager( );
            List< ResolveInfo > activityList = pm.queryIntentActivities( tweetIntent, PackageManager.MATCH_DEFAULT_ONLY );
            
            for (int i = 0; i < twitterApps.length; i++) {
                for (int j = 0; j < activityList.size( ); j++ ) {

                    final ResolveInfo app = activityList.get( j );
                    String infoName = ( String ) app.activityInfo.name;
                    
                    if ( infoName.contains( twitterApps[ i ] ) ) {
                        Log.d(LCAT, "Found activity "+infoName);
                        
                        ActivityInfo newActivity= app.activityInfo;
                        ComponentName name   = new ComponentName( newActivity.applicationInfo.packageName, newActivity.name );
                        
                        tweetIntent.setComponent( name );
                        
                        activity.startActivityForResult( tweetIntent, 0 );
                        return true;
                    }
                }
            }
        } catch ( Exception e ) {
            Log.d(LCAT, "Exeception thrown ", e);
        }
        
        Log.d(LCAT, "Nothing found");
        return false;
	}

}

